server:
  port: 8081

spring:
  application:
    name: book-service
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    region: default
    registra-fetch-interval-seconds: 5

management:
  security:
    session: never


