server:
  port: 9002
  
spring:
  application:
    name: discovery-server
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discUser:discPassword@localhost:9002/eureka
    register-with-eureka: false
    fetch-registry: false