server:
  port: 8080
  
spring:
  application:
    name: gateway-server
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5

management:
  security:
    sessions: always

zuul:
  sensitive-headers:

  routers:
    book-service:
      path: /book-service/**
    rating-service:
      path: /rating-service/**
    discovery:
      path: /discovery/**
      url: http://localhost:9002